### PR TITLE
Persistent server-side object for storing data server side

### PR DESCRIPTION
**Pull request by eirikb**
Hello.

This is a simple example of how this.user can become a persistent server-side object.
Example of usage:
index.html:

```
<script type="text/javascript">
    now.ready(function() {
        now.hello('Hello, world');
        now.world(function(msg) {
            console.log(msg);
        });
    });
</script>
```

server.js:

```
var everyone = nowjs.initialize(server);

everyone.now.hello = function(msg) {
    this.user.test = msg;
};

everyone.now.world = function(callback) {
    callback(this.user.test);
};
```

### CODE REVIEW

**Comment by tommedema** [comment]
Isn't there already a this.user object within the scope of the called function?

**Comment by eirikb** [comment]
Yes, but it is sent in every time, so it is not persistent on the server side.
As in my example would not work since test would no longer exists in the world-function.

**Comment by sridatta** [comment]
This is a good idea, eirikb . There are several other places where we create a one-time user object. I'll change those other places to use a persistent user object and then merge your pull request.

**Comment by eirikb** [comment]
Awesome

**Comment by sridatta** [comment]
Implemented in github master. npm soon.

**Pull request merged**
